place_data = {
    0: {'type': 0, 'name': 'Moscow, Russia'},
    1: {'type': 0, 'name': 'Murmansk, Russia'},
    2: {'type': 0, 'name': 'Arctic'},
    3: {'type': 0, 'name': 'Reykjavik, Iceland'},
    4: {'type': 0, 'name': 'Greenland'},
    5: {'type': 0, 'name': ''},
    6: {'type': 0, 'name': ''},
    7: {'type': 1, 'name': 'Inuvik, Canada'},
    8: {'type': 0, 'name': 'Dawson, Canada'},
    9: {'type': 0, 'name': 'McCarthy, USA'},
    10: {'type': 0, 'name': 'Anchorage, USA'},
    11: {'type': 0, 'name': 'Kodiak, USA'},
    12: {'type': 0, 'name': 'Seattle, USA'},
    13: {'type': 0, 'name': 'San Francisco, USA'},
    14: {'type': 1, 'name': 'Tucson, USA'},
    15: {'type': 0, 'name': 'Mexico, Mexico'},
    16: {'type': 0, 'name': 'Acapulco, Mexico'},
    17: {'type': 0, 'name': 'Santa Cruz'},
    18: {'type': 0, 'name': ''},
    19: {'type': 0, 'name': ''},
    20: {'type': 0, 'name': ''},
    21: {'type': 3, 'name': 'Shipwreck in Pacific'},
    22: {'type': 0, 'name': 'Santiago, Chili'},
    23: {'type': 0, 'name': 'La Paz, Bolivia'},
    24: {'type': 2, 'name': 'Porto Velho, Brazilia - come to football', 'move_to': 52},
    25: {'type': 0, 'name': 'Caracas, Venesuela'},
    26: {'type': 0, 'name': 'Santo Domingo, Dominican Republic'},
    27: {'type': 2, 'name': 'Carribean - lost in carribean', 'move_to': 17},
    28: {'type': 0, 'name': 'Panama, Panama'},
    29: {'type': 0, 'name': 'New Orleans, USA'},
    30: {'type': 0, 'name': 'Nashville, USA'},
    31: {'type': 1, 'name': 'Chicago, USA'},
    32: {'type': 0, 'name': 'Toronto, Canada'},
    33: {'type': 0, 'name': 'Quebec, Canada'},
    34: {'type': 0, 'name': 'St Jones, Canada'},
    35: {'type': 0, 'name': 'Atlantic ocean'},
    36: {'type': 0, 'name': 'Lisboa, Portugal'},
    37: {'type': 0, 'name': 'Atlantic Ocean'},
    38: {'type': 0, 'name': 'Atlantic Ocean'},
    39: {'type': 0, 'name': 'Praia, Cabo-Verde'},
    40: {'type': 0, 'name': 'Dakar, Senegal'},
    41: {'type': 0, 'name': 'Bamako, Mali'},
    42: {'type': 0, 'name': 'Marrakesh, Marokko'},
    43: {'type': 0, 'name': 'Algeria, Algeria'},
    44: {'type': 0, 'name': 'Tripoli, Libia'},
    45: {'type': 0, 'name': 'Cairo, Egypt'},
    46: {'type': 0, 'name': 'Addis-Abeba, Efiopia'},
    47: {'type': 2, 'name': 'Juba, Sudani - ride to the sea', 'move_to': 61},
    48: {'type': 2, 'name': 'Yaounde, Kamerun - lost in mirage', 'move_to': 41},
    49: {'type': 0, 'name': 'Atlantic Ocean'},
    50: {'type': 0, 'name': 'Atlantic Ocean'},
    51: {'type': 1, 'name': 'Recife, Brazil'},
    52: {'type': 0, 'name': 'Brasilia, Brasil'},
    53: {'type': 0, 'name': 'Buenos Aires, Argentina'},
    54: {'type': 0, 'name': 'Punta Arenas, Chili'},
    55: {'type': 0, 'name': 'Rio Grande, Argentina'},
    56: {'type': 0, 'name': 'Folklend Islands'},
    57: {'type': 0, 'name': 'Atlantic Ocean'},
    58: {'type': 1, 'name': 'Widhoek, Namibia'},
    59: {'type': 0, 'name': 'Luanda, Angola'},
    60: {'type': 0, 'name': 'Kinshasa, Congo'},
    61: {'type': 0, 'name': 'Mombasa, Kenya'},
    62: {'type': 0, 'name': ''},
    63: {'type': 0, 'name': ''},
    64: {'type': 0, 'name': ''},
    65: {'type': 0, 'name': ''},
    66: {'type': 0, 'name': ''},
    67: {'type': 0, 'name': ''},
    68: {'type': 2, 'name': '', 'move_to': 55},
    69: {'type': 0, 'name': ''},
    70: {'type': 2, 'name': '', 'move_to': 80},
    71: {'type': 2, 'name': '', 'move_to': 62},
    # 70: {'type': 0, 'name': ''},
    # 71: {'type': 0, 'name': ''},
    72: {'type': 0, 'name': ''},
    73: {'type': 0, 'name': ''},
    74: {'type': 0, 'name': ''},
    75: {'type': 0, 'name': ''},
    76: {'type': 0, 'name': ''},
    77: {'type': 1, 'name': ''},
    78: {'type': 0, 'name': ''},
    79: {'type': 0, 'name': ''},
    80: {'type': 0, 'name': ''},
    81: {'type': 0, 'name': ''},
    82: {'type': 0, 'name': ''},
    83: {'type': 0, 'name': ''},
    84: {'type': 0, 'name': ''},
    85: {'type': 0, 'name': ''},
    86: {'type': 0, 'name': ''},
    87: {'type': 0, 'name': ''},
    88: {'type': 0, 'name': ''},
    89: {'type': 0, 'name': ''},
    90: {'type': 0, 'name': ''},
    91: {'type': 2, 'name': '', 'move_to': 99},
    92: {'type': 0, 'name': ''},
    93: {'type': 0, 'name': ''},
    94: {'type': 0, 'name': ''},
    95: {'type': 1, 'name': ''},
    96: {'type': 0, 'name': ''},
    97: {'type': 0, 'name': ''},
    98: {'type': 0, 'name': ''},
    99: {'type': 0, 'name': ''},
    100: {'type': 2, 'name': '', 'move_to': 46},
    101: {'type': 0, 'name': ''},
    102: {'type': 0, 'name': ''},
    103: {'type': 0, 'name': ''},
    104: {'type': 0, 'name': ''},
    105: {'type': 0, 'name': ''},
    106: {'type': 0, 'name': ''},
    107: {'type': 2, 'name': '', 'move_to': 37},
    108: {'type': 0, 'name': ''},
    109: {'type': 1, 'name': ''},
    110: {'type': 0, 'name': ''},
    111: {'type': 0, 'name': ''},
    112: {'type': 0, 'name': ''},
    113: {'type': 1, 'name': ''},
    114: {'type': 0, 'name': ''},
    115: {'type': 0, 'name': ''},
    116: {'type': 0, 'name': ''},
    117: {'type': 0, 'name': ''},
    118: {'type': 0, 'name': ''},
    119: {'type': 0, 'name': ''},
    120: {'type': 0, 'name': ''},
}
